### ISSUE TITLE
マルチサイトの対応

### ISSUE THREAD

**Issue by souzouno-yakata** [skylarking85/suzuri_for_wp#1]
マルチサイトですが、インストールしても何も表示されません。マルチサイトに対応していないのでしょうか。
APIキーは取得できましたが、ユーザー名というのは、suzuriのアカウント名でしょうか。

**Comment by skylarking85** [comment]
現状単独サイトでしか操作の確認をしておりません。すみません。

> ユーザー名というのは、suzuriのアカウント名でしょうか。

そうです！
「マイショップ」のURLにある[https://suzuri.jp/{ここ}]　です。

**Comment by souzouno-yakata** [comment]
了解しました、マルチサイト対応していただけるとうれしいです。
